-- Patch: presets (versões salvas) da topologia de antenas.
-- A TV mostra o preset marcado como ativo (congelado); editar o board ao vivo não
-- afeta a TV até salvar/ativar um preset. Staff lê; admin/operador escreve.
--
-- Idempotente. Aplicar em produção (depois do patch-papeis-staff-rls.sql) com:
--   docker compose exec -T postgres \
--     psql -v ON_ERROR_STOP=1 -U uptimex_owner -d uptimex \
--     < postgres/migration/patch-antenas-presets.sql

\set ON_ERROR_STOP on

BEGIN;

-- Funções de papel (idempotente; também no patch-papeis-staff-rls.sql — repetidas
-- aqui pra este patch ser auto-suficiente).
CREATE OR REPLACE FUNCTION app_is_staff() RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public
RETURN EXISTS (SELECT 1 FROM public.usuarios WHERE id = public.app_user_id() AND ativo AND role IN ('admin','operador','visualizador'));
CREATE OR REPLACE FUNCTION app_can_operate() RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public
RETURN EXISTS (SELECT 1 FROM public.usuarios WHERE id = public.app_user_id() AND ativo AND role IN ('admin','operador'));
REVOKE ALL ON FUNCTION app_is_staff() FROM PUBLIC;
REVOKE ALL ON FUNCTION app_can_operate() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_is_staff(), app_can_operate() TO uptimex_app, uptimex_worker;

-- Tabela de presets
CREATE TABLE IF NOT EXISTS antenas_presets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(120) NOT NULL,
  dados jsonb NOT NULL,
  ativo_tv boolean NOT NULL DEFAULT false,
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_por bigint REFERENCES usuarios(id) ON DELETE SET NULL
);
-- No máximo UM preset ativo na TV por vez.
CREATE UNIQUE INDEX IF NOT EXISTS uq_antenas_presets_ativo ON antenas_presets(ativo_tv) WHERE ativo_tv;

-- Permissões (tabela nova não herda o GRANT ON ALL TABLES anterior).
GRANT SELECT, INSERT, UPDATE, DELETE ON antenas_presets TO uptimex_app;

-- RLS
ALTER TABLE antenas_presets ENABLE ROW LEVEL SECURITY;
ALTER TABLE antenas_presets FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS antenas_presets_read ON antenas_presets;
DROP POLICY IF EXISTS antenas_presets_write ON antenas_presets;
CREATE POLICY antenas_presets_read ON antenas_presets FOR SELECT TO uptimex_app
  USING (app_is_staff());
CREATE POLICY antenas_presets_write ON antenas_presets FOR ALL TO uptimex_app
  USING (app_can_operate()) WITH CHECK (app_can_operate());

COMMIT;
