\set ON_ERROR_STOP on

CREATE TYPE papel_usuario AS ENUM ('admin', 'operador', 'visualizador');
CREATE TYPE metodo_monitoramento AS ENUM ('snmp', 'ping', 'snmp+ping');
CREATE TYPE status_dispositivo AS ENUM ('online', 'offline', 'desconhecido');
CREATE TYPE status_evento AS ENUM ('online', 'offline');
CREATE TYPE status_ping AS ENUM ('online', 'offline', 'degraded');

CREATE TABLE usuarios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL UNIQUE,
  senha_hash varchar(100) NOT NULL,
  role papel_usuario NOT NULL DEFAULT 'visualizador',
  ativo boolean NOT NULL DEFAULT true,
  sessao_versao integer NOT NULL DEFAULT 1,
  avatar_url varchar(255),
  criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE empresas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(150) NOT NULL,
  descricao varchar(255), foto_url varchar(255), endereco varchar(255),
  latitude double precision CHECK (latitude BETWEEN -90 AND 90),
  longitude double precision CHECK (longitude BETWEEN -180 AND 180),
  criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuario_empresas (
  usuario_id bigint NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  empresa_id bigint NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (usuario_id, empresa_id)
);

CREATE TABLE dispositivos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  nome varchar(150) NOT NULL, ip inet NOT NULL,
  fabricante varchar(50) NOT NULL DEFAULT 'generico',
  metodo_monitoramento metodo_monitoramento NOT NULL DEFAULT 'snmp+ping',
  comunidade_snmp varchar(500),
  porta_snmp integer NOT NULL DEFAULT 161 CHECK (porta_snmp BETWEEN 1 AND 65535),
  intervalo_polling_seg integer NOT NULL DEFAULT 30 CHECK (intervalo_polling_seg BETWEEN 5 AND 3600),
  status_atual status_dispositivo NOT NULL DEFAULT 'desconhecido',
  ultima_verificacao timestamp without time zone,
  latencia_ms real CHECK (latencia_ms IS NULL OR latencia_ms >= 0),
  perda_pct real CHECK (perda_pct IS NULL OR perda_pct BETWEEN 0 AND 100),
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (id, empresa_id)
);

CREATE TABLE ping_metricas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispositivo_id bigint NOT NULL REFERENCES dispositivos(id) ON DELETE CASCADE,
  latencia_ms real CHECK (latencia_ms IS NULL OR latencia_ms >= 0),
  perda_pct real NOT NULL DEFAULT 0 CHECK (perda_pct BETWEEN 0 AND 100),
  "timestamp" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Series temporais de ping (raw + rollups horario/diario). Alimentadas pelo motor
-- (uptimex_worker) e lidas nos historicos por empresa. device_id/empresa_id
-- denormalizados para o RLS por empresa nao precisar de JOIN.
CREATE TABLE ping_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" timestamp(3) without time zone NOT NULL,
  device_id bigint NOT NULL REFERENCES dispositivos(id) ON DELETE CASCADE,
  empresa_id bigint NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  latency_ms double precision,
  packet_loss double precision NOT NULL,
  status status_ping NOT NULL,
  UNIQUE (device_id, "timestamp")
);

CREATE TABLE ping_log_hourly (
  device_id bigint NOT NULL REFERENCES dispositivos(id) ON DELETE CASCADE,
  empresa_id bigint NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  bucket_start timestamp without time zone NOT NULL,
  sample_count integer NOT NULL,
  latency_sample_count integer NOT NULL,
  avg_latency double precision,
  min_latency double precision,
  max_latency double precision,
  packet_loss_pct double precision NOT NULL,
  uptime_pct double precision NOT NULL,
  degraded_pct double precision NOT NULL,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (device_id, bucket_start)
);

CREATE TABLE ping_log_daily (
  device_id bigint NOT NULL REFERENCES dispositivos(id) ON DELETE CASCADE,
  empresa_id bigint NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  bucket_start date NOT NULL,
  sample_count integer NOT NULL,
  latency_sample_count integer NOT NULL,
  avg_latency double precision,
  min_latency double precision,
  max_latency double precision,
  packet_loss_pct double precision NOT NULL,
  uptime_pct double precision NOT NULL,
  degraded_pct double precision NOT NULL,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (device_id, bucket_start)
);

CREATE TABLE status_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispositivo_id bigint NOT NULL REFERENCES dispositivos(id) ON DELETE CASCADE,
  status status_evento NOT NULL, inicio timestamp without time zone NOT NULL,
  fim timestamp without time zone,
  duracao_segundos integer CHECK (duracao_segundos IS NULL OR duracao_segundos >= 0),
  CHECK (fim IS NULL OR fim >= inicio)
);

CREATE TABLE topologia_nodes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  dispositivo_id bigint, label varchar(150) NOT NULL,
  tipo varchar(30) NOT NULL DEFAULT 'outro', pos_x real NOT NULL DEFAULT 0, pos_y real NOT NULL DEFAULT 0,
  UNIQUE (id, empresa_id),
  FOREIGN KEY (dispositivo_id, empresa_id)
    REFERENCES dispositivos(id, empresa_id) ON DELETE SET NULL (dispositivo_id)
);

CREATE TABLE topologia_viewport (
  empresa_id bigint PRIMARY KEY REFERENCES empresas(id) ON DELETE CASCADE,
  pos_x real NOT NULL DEFAULT 0, pos_y real NOT NULL DEFAULT 0,
  zoom real NOT NULL DEFAULT 1 CHECK (zoom > 0)
);

CREATE TABLE topologia_edges (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  node_origem bigint NOT NULL, node_destino bigint NOT NULL, label varchar(100),
  FOREIGN KEY (node_origem, empresa_id) REFERENCES topologia_nodes(id, empresa_id) ON DELETE CASCADE,
  FOREIGN KEY (node_destino, empresa_id) REFERENCES topologia_nodes(id, empresa_id) ON DELETE CASCADE,
  CHECK (node_origem <> node_destino)
);

CREATE TABLE links_dedicados (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  bloco cidr NOT NULL, descricao varchar(255),
  criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE configuracoes (chave varchar(60) PRIMARY KEY, valor text);

CREATE TABLE usuario_sessoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id bigint NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  token_hash char(64) NOT NULL UNIQUE,
  sessao_versao integer NOT NULL,
  expires_at timestamp without time zone NOT NULL,
  revoked_at timestamp without time zone,
  last_used_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip_origem inet,
  user_agent varchar(255)
);

CREATE TABLE mcp_api_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash char(64) NOT NULL UNIQUE,
  token_prefix varchar(24) NOT NULL,
  empresa_id bigint REFERENCES empresas(id) ON DELETE CASCADE,
  escopo_global boolean NOT NULL DEFAULT false,
  expires_at timestamp without time zone NOT NULL,
  last_used_at timestamp without time zone,
  revoked_at timestamp without time zone,
  criada_por bigint REFERENCES usuarios(id) ON DELETE SET NULL,
  criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK ((escopo_global AND empresa_id IS NULL) OR (NOT escopo_global AND empresa_id IS NOT NULL))
);

CREATE TABLE auditoria (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id bigint REFERENCES usuarios(id) ON DELETE SET NULL,
  empresa_id bigint REFERENCES empresas(id) ON DELETE SET NULL,
  usuario varchar(100) NOT NULL, acao varchar(50) NOT NULL,
  entidade varchar(50) NOT NULL, entidade_id bigint, detalhes text,
  ip_origem inet, pais varchar(5), regiao varchar(10), cidade varchar(100),
  "timestamp" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Modulo Antenas: board GLOBAL do provedor (nao e por empresa). E a
-- infraestrutura wireless/torres do NOC, administrada so por admins. Sem
-- empresa_id: o RLS abaixo restringe leitura/escrita a app_is_admin().
CREATE TABLE antenas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(150) NOT NULL, ip inet NOT NULL,
  fabricante varchar(50) NOT NULL DEFAULT 'ubiquiti', modelo varchar(100),
  tipo_wireless varchar(50) NOT NULL DEFAULT 'ptp_master',
  frequencia_mhz integer, largura_canal_mhz integer, ssid varchar(100), sinal_esperado_dbm integer,
  intervalo_polling_seg integer NOT NULL DEFAULT 10 CHECK (intervalo_polling_seg BETWEEN 2 AND 3600),
  status_atual status_dispositivo NOT NULL DEFAULT 'desconhecido',
  latencia_ms real CHECK (latencia_ms IS NULL OR latencia_ms >= 0),
  perda_pct real CHECK (perda_pct IS NULL OR perda_pct BETWEEN 0 AND 100),
  ultima_verificacao timestamp without time zone, ativo boolean NOT NULL DEFAULT true,
  criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE antenas_nodes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  antena_id bigint REFERENCES antenas(id) ON DELETE CASCADE,
  label varchar(150) NOT NULL,
  tipo_visual varchar(50) NOT NULL DEFAULT 'antena_ptp',
  pos_x real NOT NULL DEFAULT 0, pos_y real NOT NULL DEFAULT 0,
  criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE antenas_enlaces (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origem_node_id bigint NOT NULL REFERENCES antenas_nodes(id) ON DELETE CASCADE,
  destino_node_id bigint NOT NULL REFERENCES antenas_nodes(id) ON DELETE CASCADE,
  tipo_enlace varchar(50) NOT NULL DEFAULT 'ptp_wireless', label varchar(100), frequencia varchar(50),
  distancia_km real CHECK (distancia_km IS NULL OR distancia_km >= 0),
  capacidade_mbps integer CHECK (capacidade_mbps IS NULL OR capacidade_mbps >= 0),
  cor varchar(20), curvo boolean NOT NULL DEFAULT false,
  espessura real, estilo varchar(20), animado boolean,
  criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (origem_node_id <> destino_node_id)
);

-- Board unico: uma linha (id = 1) guarda o enquadramento salvo do mapa.
CREATE TABLE antenas_viewport (
  id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  pos_x real NOT NULL DEFAULT 0, pos_y real NOT NULL DEFAULT 0,
  zoom real NOT NULL DEFAULT 1 CHECK (zoom > 0)
);

CREATE TABLE antenas_metricas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  antena_id bigint NOT NULL REFERENCES antenas(id) ON DELETE CASCADE,
  latencia_ms real CHECK (latencia_ms IS NULL OR latencia_ms >= 0),
  perda_pct real NOT NULL DEFAULT 0 CHECK (perda_pct BETWEEN 0 AND 100),
  "timestamp" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_usuario_empresas_empresa ON usuario_empresas(empresa_id, usuario_id);
CREATE INDEX idx_usuario_sessoes_ativas ON usuario_sessoes(usuario_id, revoked_at, expires_at);
CREATE INDEX idx_mcp_api_keys_ativas ON mcp_api_keys(token_hash, revoked_at, expires_at);
CREATE INDEX idx_dispositivos_empresa ON dispositivos(empresa_id);
CREATE INDEX idx_ping_metricas_disp ON ping_metricas(dispositivo_id, "timestamp");
-- Leitura de historico por empresa (device/range ja coberto por UNIQUE/PK).
CREATE INDEX idx_ping_log_empresa_timestamp ON ping_log(empresa_id, "timestamp");
CREATE INDEX idx_ping_log_hourly_empresa_bucket ON ping_log_hourly(empresa_id, bucket_start);
CREATE INDEX idx_ping_log_daily_empresa_bucket ON ping_log_daily(empresa_id, bucket_start);
CREATE INDEX idx_status_eventos_dispositivo ON status_eventos(dispositivo_id, inicio);
CREATE UNIQUE INDEX uq_status_evento_aberto ON status_eventos(dispositivo_id) WHERE fim IS NULL;
CREATE INDEX idx_topologia_nodes_empresa ON topologia_nodes(empresa_id);
CREATE INDEX idx_topologia_edges_empresa ON topologia_edges(empresa_id);
CREATE INDEX idx_links_empresa ON links_dedicados(empresa_id);
CREATE INDEX idx_auditoria_empresa_timestamp ON auditoria(empresa_id, "timestamp" DESC);
CREATE INDEX idx_antenas_nodes_antena ON antenas_nodes(antena_id);
CREATE INDEX idx_antenas_enlaces_origem ON antenas_enlaces(origem_node_id);
CREATE INDEX idx_antenas_enlaces_destino ON antenas_enlaces(destino_node_id);
CREATE INDEX idx_antenas_metricas_antena ON antenas_metricas(antena_id, "timestamp");

REVOKE ALL ON SCHEMA public FROM PUBLIC;
